### PR TITLE
Add Windows Support

### PR DESCRIPTION
**Pull request by zhudock**
For topics discussed in #3
Add Windows support
Use only a single input (connect string)

Also added notes to README.md

### CODE REVIEW

**Comment by tschf** [comment]
Awesome. One tweak - SQLcl has it's own space on OTN, with the download page being http://www.oracle.com/technetwork/developer-tools/sqlcl/downloads/index.html, did you want to update the links to that page instead?

**Comment by zhudock** [comment]
Thanks. Wasn't aware of that link. I'll get that change committed first thing tomorrow.

**Comment by zhudock** [comment]
The links have been updated. Thanks for pointing out the dedicated OTN page

**Comment by tschf** [comment]
No problem, thanks for the contributions!

**Pull request merged**
